version: '3'
services:
  tesseract:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - TAG=noble-0.31.0
    container_name: tesseract_planning
    image: ghcr.io/tesseract-robotics/trajopt_deploy:noble-0.31.0
    stdin_open: true
    tty: true
    network_mode: host
    user: ${CURRENT_UID}  # CURRENT_UID=$(id -u):$(id -g)
