import re, StringIO
def make_fwd_header(fnames, outfile, namespaces = []):
    classes = []
    for header in fnames:
        
        with open(header, "r") as fh:
            classes.extend(find_classes(fh.read()))
    with open(outfile, "w") as fh:
        print >>fh, "// autogenerated forward declaration header"
        print >>fh, "#pragma once"    
        print >>fh, "#include <memory>"
        for ns in namespaces:
            print >>fh, "namespace %s {"%ns
        for name in classes:
            d = dict(name=name)
            print >>fh, "class %(name)s;"%d
            print >>fh, "typedef std::shared_ptr<%(name)s> %(name)sPtr;"%d
        print >>fh, "}"*len(namespaces)

def find_classes(text):
    """
    find line that contains a top-level open brace
    then look for class { in that line
    """
    nest_level = 0
    brace_re = re.compile("[\{\}]")
    classname_re = "[\w\<\>\:]+"
    class_re = re.compile(
        "(?:class|struct)\s*(\w+)\s*(?:\:\s*public\s*" 
        + classname_re  + "(?:,\s*public\s*" + classname_re + ")*)?\s*\{")
    
    classes = []
    lines = text.split("\n")
    for (i,line) in enumerate(lines):
        if True:#nest_level == 0 and (i==0 or "template" not in lines[i-1]):            
            classes.extend(class_re.findall(line))
        
        braces = brace_re.findall(line)
        for brace in braces:
            if brace == "{": nest_level += 1
            elif brace == "}": nest_level -= 1
            
    return classes
