name: CMake-Format

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 5 * * *'

jobs:
  cmake_lang:
    name: Format
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Run CMake Lang Format Check
        run: |
          sudo pip3 install cmakelang
          ./.run-cmake-format
          output=$(git diff)
          if [ -n "$output" ]; then exit 1; else exit 0; fi
