name: Package-Debian-Build

on:
  push:
    tags:
      - '*'

  # allow manually starting this workflow
  workflow_dispatch:
    inputs:
      major_version:
        description: 'Major Version'
        required: true
        type: string
      minor_version:
        description: 'Minor Version'
        required: true
        type: string
      patch_version:
        description: 'Patch Version'
        required: true
        type: string

jobs:
  Debian:
    name: ${{ matrix.distro }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: [jammy, noble]
    container:
      image: ghcr.io/tesseract-robotics/tesseract:${{ matrix.distro }}-${{ github.event.inputs.major_version }}.${{ github.event.inputs.minor_version }}
      env:
        DEBIAN_FRONTEND: noninteractive
        TZ: Etc/UTC

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          path: target_ws/src
          ref: ${{ github.event.inputs.major_version }}.${{ github.event.inputs.minor_version }}.${{ github.event.inputs.patch_version }}

      - name: Install dependencies
        run: |
          apt update
          apt upgrade -y
          apt install -y clang-tidy

      - name: Build and test
        uses: tesseract-robotics/colcon-action@v14
        with:
          before-script: source /opt/tesseract/install/setup.bash
          ccache-enabled: false
          upstream-args: --cmake-args -DCMAKE_BUILD_TYPE=Release
          target-path: target_ws/src
          target-args: --cmake-args -DCMAKE_BUILD_TYPE=Release -DTRAJOPT_PACKAGE=ON
          run-tests: false

      - name: Create artifacts directory
        run: |
          mkdir $GITHUB_WORKSPACE/artifacts

      - name: Package osqp
        shell: bash
        run: |
          if [ -d $GITHUB_WORKSPACE/target_ws/build/osqp ]; then
            cd $GITHUB_WORKSPACE/target_ws/build/osqp
            cpack --config CPackConfig.cmake
            cp ./*.deb $GITHUB_WORKSPACE/artifacts
            cp ./*.tar.xz $GITHUB_WORKSPACE/artifacts
          fi

      - name: Package osqp_eigen
        shell: bash
        run: |
          if [ -d $GITHUB_WORKSPACE/target_ws/build/osqp_eigen ]; then
            cd $GITHUB_WORKSPACE/target_ws/build/osqp_eigen
            cpack --config CPackConfig.cmake
            cp ./*.deb $GITHUB_WORKSPACE/artifacts
            cp ./*.tar.xz $GITHUB_WORKSPACE/artifacts
          fi

      - name: Package qpoases
        shell: bash
        run: |
          if [ -d $GITHUB_WORKSPACE/target_ws/build/qpoases ]; then
            cd $GITHUB_WORKSPACE/target_ws/build/qpoases
            cpack --config CPackConfig.cmake
            cp ./*.deb $GITHUB_WORKSPACE/artifacts
            cp ./*.tar.xz $GITHUB_WORKSPACE/artifacts
          fi

      - name: Package trajopt_common
        working-directory: target_ws/build/trajopt_common
        shell: bash
        run: |
          cpack --config CPackConfig.cmake
          cp ./*.deb $GITHUB_WORKSPACE/artifacts
          cp ./*.tar.xz $GITHUB_WORKSPACE/artifacts

      - name: Package trajopt_sco
        working-directory: target_ws/build/trajopt_sco
        shell: bash
        run: |
          cpack --config CPackConfig.cmake
          cp ./*.deb $GITHUB_WORKSPACE/artifacts
          cp ./*.tar.xz $GITHUB_WORKSPACE/artifacts

      - name: Package trajopt
        working-directory: target_ws/build/trajopt
        shell: bash
        run: |
          cpack --config CPackConfig.cmake
          cp ./*.deb $GITHUB_WORKSPACE/artifacts
          cp ./*.tar.xz $GITHUB_WORKSPACE/artifacts

      - name: Package trajopt_sqp
        working-directory: target_ws/build/trajopt_sqp
        shell: bash
        run: |
          cpack --config CPackConfig.cmake
          cp ./*.deb $GITHUB_WORKSPACE/artifacts
          cp ./*.tar.xz $GITHUB_WORKSPACE/artifacts

      - name: Package trajopt_ifopt
        working-directory: target_ws/build/trajopt_ifopt
        shell: bash
        run: |
          cpack --config CPackConfig.cmake
          cp ./*.deb $GITHUB_WORKSPACE/artifacts
          cp ./*.tar.xz $GITHUB_WORKSPACE/artifacts

      - uses: actions/upload-artifact@v7
        with:
          name: debian_package_${{ matrix.distro }}
          path: ${{ github.workspace }}/artifacts/*.deb

      - uses: actions/upload-artifact@v7
        with:
          name: archive_package_${{ matrix.distro }}
          path: ${{ github.workspace }}/artifacts/*.tar.xz
