name: Ubuntu

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 5 * * *'

jobs:
  ci:
    name: ${{ matrix.distro }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: [focal, jammy]
    container:
      image: ubuntu:${{ matrix.distro }}
      env:
        CCACHE_DIR: "$GITHUB_WORKSPACE/${{ matrix.distro }}/.ccache"
        DEBIAN_FRONTEND: noninteractive
        TZ: Etc/UTC
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: target_ws/src

      - name: Install Depends
        shell: bash
        run: |
          apt update
          apt upgrade -y
          apt install -y cmake curl lsb-release ca-certificates gnupg python3 python3-distutils python3-pip ccache git clang-tidy liboctomap-dev
          python3 -m pip install vcstool -q
          python3 -m pip install colcon-common-extensions -q
          python3 -m pip install rosdep -q
          rosdep init
          rosdep update
          cd $GITHUB_WORKSPACE/target_ws/src
          curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null
          apt update -qq

      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")

      - name: ccache cache files
        continue-on-error: true
        uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.distro }}/.ccache
          key: ${{ matrix.distro }}-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
          restore-keys: |
            ${{ matrix.distro }}-ccache-

      - name: Build Upstream Workspace
        shell: bash
        run: |
          mkdir -p $GITHUB_WORKSPACE/upstream_ws/src
          vcs import --input "$GITHUB_WORKSPACE/target_ws/src/dependencies.repos" $GITHUB_WORKSPACE/upstream_ws/src/
          cd $GITHUB_WORKSPACE/upstream_ws
          rosdep install --from-paths src --ignore-src -r -y
          colcon build --event-handlers console_direct+ --cmake-args -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_BUILD_TYPE=Release
          if [ $? -ge 1 ]; then return 1; fi

      - name: Build Target Workspace
        shell: bash
        run: |
          source $GITHUB_WORKSPACE/upstream_ws/install/setup.bash
          cd $GITHUB_WORKSPACE/target_ws
          rosdep install --from-paths src --ignore-src -r -y
          colcon build --event-handlers console_direct+ --cmake-args -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_BUILD_TYPE=Debug -DTRAJOPT_ENABLE_TESTING=ON -DTRAJOPT_ENABLE_CLANG_TIDY=ON
          if [ $? -ge 1 ]; then return 1; fi

      - name: Run Tests
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/target_ws
          source $GITHUB_WORKSPACE/target_ws/install/setup.bash
          colcon test --event-handlers console_direct+ --return-code-on-test-failure
          if [ $? -ge 1 ]; then return 1; fi
          colcon test-result --verbose
          if [ $? -ge 1 ]; then return 1; fi
